[package]
name = "yap"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
better-panic = "0.3.0"
chrono = "0.4.39"
color-eyre = "0.6.3"
human-panic = "2.0.2"
libc = "0.2.169"
# log = "0.4.25"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
ratatui-macros = "0.6.0"
rolling-file = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serialport = "4.7.0"
strip-ansi-escapes = "0.2.1"
tracing = { version = "0.1.41", features = ["log"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "env-filter"] }
tui-input = "0.11.1"
virtual-serialport = "0.1.3"

# Enable when flamegraphing
# [profile.release]
# debug = true

# Speeds up rendering operations for debug builds
[profile.dev.package.ratatui]
opt-level = 3
