[package]
name = "yap"
version = "0.1.0"
edition = "2021"

[features]
default = []
# TODO
espflash = ["dep:espflash"]

[dependencies]
ansi-to-tui = "7.0.0"
arboard = "3.4.1"
arc-swap = "1.7.1"
better-panic = "0.3.0"
chrono = "0.4.39"
color-eyre = "0.6.3"
derivative = "2.2.0"
enum-rotate = "0.1.1"
espflash = { version = "3.3.0", optional = true }
human-panic = "2.0.2"
int-enum = { git = "https://github.com/nullstalgia/int-enum-rs", branch = "feat/colors-and-discriminators" }
libc = "0.2.169"
memchr = "2.7.4"
# log = "0.4.25"
# num_enum = "0.7.3"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
ratatui-macros = "0.6.0"
rolling-file = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serialport = { version = "4.7.0", features = ["serde"] }
strip-ansi-escapes = "0.2.1"
struct-table = { path = "struct-table" }
strum = { version = "0.27", features = ["derive"] }
takeable = "0.2.2"
tracing = { version = "0.1.41", features = ["log"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "env-filter"] }
tui-big-text = "0.7.1"
tui-input = "0.11.1"
virtual-serialport = "0.1.3"

# Enable when flamegraphing
# [profile.release]
# debug = true

# Speeds up rendering operations for debug builds
[profile.dev.package.ratatui]
opt-level = 3
