[package]
name = "yap"
version = "0.1.0"
edition = "2021"

[dependencies]
better-panic = "0.3.0"
chrono = "0.4.39"
color-eyre = "0.6.3"
human-panic = "2.0.2"
libc = "0.2.169"
# log = "0.4.25"
ratatui = "0.29.0"
ratatui-macros = "0.6.0"
rolling-file = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serialport = "4.7.0"
strip-ansi-escapes = "0.2.1"
tracing = { version = "0.1.41", features = ["log"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "env-filter"] }
tui-input = "0.11.1"
