[[regex]]
rule = '^\[\s*\d+\]\[D\]\[[^\]:]+(?::\d+)?\]'
color = "blue"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[I\]\[[^\]:]+(?::\d+)?\]'
color = "green"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[E\]\[[^\]:]+(?::\d+)?\]'
color = "red"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[W\]\[[^\]:]+(?::\d+)?\]'
color = "yellow"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[V\]\[[^\]:]+(?::\d+)?\]'
color = "magenta"
line = true

[[regex]]
rule = '(?i)lorem'
color = "cyan"

[[regex]]
rule = "(?i)OpenShock"
color = "BrightCyan"

[[regex]]
# \x1B[K
rule = '(?-u)\x1b\x5b\x4b'
color = "red"
line = true

# Censor scanned networks from OpenShock captive portal
[[regex]]
rule = '[Nn]etwork\s+(.+?)\s*\(([0-9A-Fa-f:]+)\)'
censor = true
