# For Pi 1B, ARM v6 + Hard Float
[target.arm-unknown-linux-gnueabihf]
pre-build = [
    # So a lot of Debian packages on this target incorrectly build for
    # ARM v7, which can cause some illegal operations.
    # But when testing it, it *seems* fine, but egh. I'd like something more graceful.
    "rm /etc/apt/preferences.d/all-packages",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install --no-install-recommends libudev-dev:$CROSS_DEB_ARCH",
]
