# Color Highlight Rule Example: case-insensitive match
# Example
# [[regex]] ## type of rule (regex/literal)
# rule = '(?i)lorem' ## rule contents
# line = true ## affect the whole line if any match found within
# color = "cyan" ## ansi/hex color to highlight matches (optional if any below used)
# censor = false ## if true, replace the matched content (or whole line) with `*`
# hide = false ## if true, remove the matched content (or whole line) entirely.

# Note: hidden/censored contents are still saved to log files raw.

[[regex]]
rule = '^\[\s*\d+\]\[D\]\[[^\]:]+(?::\d+)?\]'
color = "blue"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[I\]\[[^\]:]+(?::\d+)?\]'
color = "green"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[E\]\[[^\]:]+(?::\d+)?\]'
color = "red"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[W\]\[[^\]:]+(?::\d+)?\]'
color = "yellow"
line = true

[[regex]]
rule = '^\[\s*\d+\]\[V\]\[[^\]:]+(?::\d+)?\]'
color = "magenta"
line = true

[[regex]]
rule = '(?i)lorem'
color = "cyan"

[[regex]]
rule = "(?i)OpenShock"
color = "BrightCyan"

[[regex]]
# \x1B[K
rule = '(?-u)\x1b\x5b\x4b'
color = "red"
line = true

# Censor scanned networks from OpenShock captive portal
[[regex]]
rule = '[Nn]etwork\s+(.+?)\s*\(([0-9A-Fa-f:]+)\)'
censor = true
