[keybindings]
ctrl-w = "toggle-textwrap"
ctrl-o = "toggle-dtr"
ctrl-p = "toggle-rts"
ctrl-e = "show-espflash"
# ctrl-e = "reload-macros"
# ctrl-e = "esp-bootloader"
ctrl-t = "toggle-timestamps"
ctrl-m = "show-macros"
ctrl-b = "show-behavior"
'ctrl-.' = "show-portsettings"
# ctrl-d = "toggle-indices"
ctrl-d = "show-defmt"
ctrl-f = "reload-colors"
F20 = "esp-hard-reset"
F21 = "esp-bootloader"
shift-F21 = "esp-bootloader-unchecked"
ctrl-z = "esp-bootloader-unchecked"
ctrl-r = "show-rendering"
ctrl-h = "toggle-hex"
ctrl-l = "show-logging"
ctrl-k = "show-keybinds"

# macros
F19 = "Restart"
ctrl-s = "CaiX Vib (ID 12345, 0.5s)"
ctrl-g = "OpenShock Setup|Echo Off"
ctrl-j = ["PAUSE_MS:2000", "OpenShock Setup|Factory Reset", "PAUSE_MS:2000", "OpenShock Setup|Factory Reset"]

# espflash profiles
F18 = ["Core v2 1.4.0", "pause_ms:1000", "CaiX Vib (ID 12345, 1s)", "Echo Off", "Setup Authtoken and Networks"]
shift-F18 = ["esp-erase-flash", "Core v2 1.4.0"]
