category = "OpenShock" ## category is optional, if missing, will use file name

[[macro]]
name = "Version"
content = "version"

[[macro]]
name = "Restart"
content = "restart"

[[macro]]
name = "System Info"
content = "sysinfo"

[[macro]]
name = "Get Config (JSON)"
content = "jsonconfig"

[[macro]]
name = "Get Config (Raw)"
content = "rawconfig"
