# From: https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases
name: Release

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Dependencies (Linux)
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: yap
          features: portable
          target: ${{ matrix.target }}
          include: LICENSE,README.md
          tar: unix
          zip: windows
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha512
      # - uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: "**/*.tar.gz,**/*.zip"
